[package]
name = "valkey-manager"
version = "0.2.0"
description = "Native desktop client for Valkey"
authors = ["Lucas Eufrasio"]
edition = "2021"

[lib]
name = "valkey_manager_lib"
crate-type = ["rlib"]

[dependencies]
directories = "6.0.0"
eframe = { version = "0.36.2", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
fred = { version = "7.0.0", features = ["tokio-rustls", "sentinel-client"] }
futures-util = "0.3.31"
image = { version = "0.25.10", default-features = false, features = ["png"] }
keyring = "4.2.0"
serde = { version = "1", features = ["derive"] }
shlex = "2.0.1"
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["full"] }
toml = "1.1.6"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
url = "2.5.8"
uuid = { version = "1.26.1", features = ["serde", "v4"] }

[dev-dependencies]
tempfile = "3.27.0"
